#!/usr/bin/env python3
"""
Single-neuron SPICE vs Gilgamesh comparison tool.

Compares the membrane voltage dynamics of a single LIF neuron between:
1. ngspice simulation (using the pulse-stretch neuron generator)
2. Gilgamesh Rust implementation

Usage:
    python tools/neuron_compare.py --input-current 1e-6 --duration 0.05
    python tools/neuron_compare.py --neuron-config path/to/neuron.json
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

# Add SPICE neuronSim to path for importing the generator
SCRIPT_DIR = Path(__file__).resolve().parent
GILGAMESH_ROOT = SCRIPT_DIR.parent
TARSKII_ROOT = GILGAMESH_ROOT.parent
SPICE_NEURON_SIM = TARSKII_ROOT / "SPICE" / "neuronSim"

sys.path.insert(0, str(SPICE_NEURON_SIM))

try:
    import matplotlib.pyplot as plt
    HAS_MATPLOTLIB = True
except ImportError:
    HAS_MATPLOTLIB = False
    plt = None


@dataclass
class NeuronParams:
    """Parameters for single neuron comparison."""
    # Membrane
    c_mem: float = 10e-9       # 10 nF
    r_leak: float = 120e3      # 120 kOhm -> tau = 1.2 ms

    # Threshold
    vdd: float = 5.0
    vref: float = 2.5
    threshold_over_vref: float = 0.8  # Threshold at Vref + 0.8V = 3.3V

    # Pulse stretching
    tau_pulse: float = 1.67e-3  # 1.67 ms

    # Simulation
    dt: float = 1e-6           # 1 us timestep
    duration: float = 0.05     # 50 ms total

    # Input
    input_current: float = 1e-6  # 1 uA constant input

    @property
    def tau_m(self) -> float:
        return self.c_mem * self.r_leak

    @property
    def num_steps(self) -> int:
        return int(self.duration / self.dt)

    def to_neuron_json(self) -> dict:
        """Convert to the JSON format expected by the SPICE generator."""
        # Calculate pulse stretch R and C from tau
        # tau = R * C, use C = 100nF, solve for R
        c_pw = 100e-9
        r_pw = self.tau_pulse / c_pw

        return {
            "name": "test_neuron",
            "supplies": {"vdd": self.vdd, "vref": self.vref},
            "membrane": {"C_mem_F": self.c_mem, "R_leak_ohm": self.r_leak},
            "threshold": {
                "over_vref_V": self.threshold_over_vref,
                "hysteresis_V": 0.05,
                "C_adapt_F": 22e-9,
                "divider_scale": 5.0
            },
            "reset": {
                "enable": True,
                "series_R_ohm": 200.0,
                "mux_Ron_ohm": 10.0,
                "mux_Roff_ohm": 1e9,
                "mux_Coff_F": 7e-12,
                "switch_Vt": 2.5,
                "switch_Vh": 0.1
            },
            "comparator": {
                "offset_V": 0.003,
                "prop_delay_s": 40e-9,
                "vlow_V": 0.0,
                "vhigh_V": self.vdd,
                "gain_fast": 2000.0
            },
            "analog_out": {
                "gain": 1.0,
                "sign": 1,
                "clamp_to_rails": False,
                "analog_out_R_ohm": 10e3,
                "inverting": True,
                "R1_ohm": 10e3,
                "R2_ohm": 10e3,
                "bias_current_A": 10e-6
            },
            "bias_currents": {"tia_A": 20e-6, "comparator_A": 2e-6},
            "simulation": {"tstop_s": self.duration, "tstep_s": self.dt},
            "pulse_stretch": {
                "enable": True,
                "R_pw_ohm": r_pw,
                "C_pw_F": c_pw
            }
        }


def generate_spice_netlist(params: NeuronParams, output_dir: Path) -> Path:
    """Generate a single-neuron SPICE netlist with constant current input."""
    from lif_neuron_generator_pulse_stretch import NeuronConfig, generate_detailed_neuron

    # Write neuron config JSON
    neuron_json = params.to_neuron_json()
    neuron_json_path = output_dir / "neuron_config.json"
    with open(neuron_json_path, 'w') as f:
        json.dump(neuron_json, f, indent=2)

    # Load config and generate subcircuit
    cfg = NeuronConfig.load(str(neuron_json_path))
    subckt = generate_detailed_neuron(cfg)

    # Write subcircuit
    subckt_path = output_dir / "neuron.subckt"
    with open(subckt_path, 'w') as f:
        f.write(subckt)

    # Generate full netlist with test bench (use absolute paths)
    subckt_abs = subckt_path.resolve()
    csv_abs = (output_dir / 'spice_output.csv').resolve()

    netlist = f"""* Single LIF Neuron Test - Gilgamesh Comparison
* Generated by neuron_compare.py

.include {subckt_abs}

* Power supplies
Vdd vdd 0 DC {params.vdd}
Vref vref 0 DC {params.vref}

* Neuron instance
* Pins: mem vref vdd comp_pulse analog_out sum
Xneuron mem vref vdd comp_pulse analog_out sum test_neuron_detailed

* Constant current input (into sum node)
Iin 0 sum DC {params.input_current}

* Initial conditions
.ic V(mem)={params.vref} V(sum)={params.vref}

* Transient analysis
.tran {params.dt} {params.duration} 0 {params.dt}

* Save data
.control
run
wrdata {csv_abs} v(mem) v(comp_pulse) v(sum)
.endc

.end
"""

    netlist_path = output_dir / "test_neuron.cir"
    with open(netlist_path, 'w') as f:
        f.write(netlist)

    return netlist_path


def run_ngspice(netlist_path: Path, output_dir: Path) -> Optional[Path]:
    """Run ngspice and return path to output CSV."""
    ngspice = shutil.which("ngspice")
    if ngspice is None:
        print("ERROR: ngspice not found in PATH")
        return None

    log_path = output_dir / "ngspice.log"
    netlist_abs = netlist_path.resolve()

    print(f"Running ngspice: {netlist_abs}")
    result = subprocess.run(
        [ngspice, "-b", str(netlist_abs)],
        cwd=str(output_dir.resolve()),
        capture_output=True,
        text=True
    )

    with open(log_path, 'w') as f:
        f.write(result.stdout)
        if result.stderr:
            f.write("\n--- STDERR ---\n")
            f.write(result.stderr)

    if result.returncode != 0:
        print(f"ngspice failed with code {result.returncode}")
        print(result.stderr[:500] if result.stderr else "No stderr")
        return None

    csv_path = output_dir / "spice_output.csv"
    if not csv_path.exists():
        print(f"Expected output CSV not found: {csv_path}")
        return None

    return csv_path


def parse_spice_csv(csv_path: Path) -> Tuple[List[float], List[float], List[float]]:
    """Parse ngspice wrdata output. Returns (times, v_mem, v_spike)."""
    times = []
    v_mem = []
    v_spike = []

    with open(csv_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('*') or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) >= 3:
                try:
                    t = float(parts[0])
                    vm = float(parts[1])
                    vs = float(parts[2]) if len(parts) > 2 else 0.0
                    times.append(t)
                    v_mem.append(vm)
                    v_spike.append(vs)
                except ValueError:
                    continue

    return times, v_mem, v_spike


def run_gilgamesh_neuron(params: NeuronParams, output_dir: Path) -> Optional[Path]:
    """Run Gilgamesh single-neuron simulation."""
    # Build gilgamesh if needed
    print("Building Gilgamesh...")
    result = subprocess.run(
        ["cargo", "build", "--release"],
        cwd=str(GILGAMESH_ROOT),
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(f"cargo build failed: {result.stderr[:500]}")
        return None

    # Run the neuron-test command
    csv_path = output_dir / "gilgamesh_output.csv"

    cmd = [
        str(GILGAMESH_ROOT / "target" / "release" / "gilgamesh"),
        "neuron-test",
        "--tau-m", str(params.tau_m),
        "--dt", str(params.dt),
        "--threshold", str(params.threshold_over_vref + params.vref),
        "--vref", str(params.vref),
        "--input-current", str(params.input_current),
        "--duration", str(params.duration),
        "--output", str(csv_path),
    ]

    if params.tau_pulse > 0:
        cmd.extend(["--tau-pulse", str(params.tau_pulse)])

    print(f"Running Gilgamesh: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        print(f"Gilgamesh neuron-test failed: {result.stderr}")
        # Check if command exists
        if "neuron-test" in result.stderr or "unrecognized" in result.stderr.lower():
            print("\nNOTE: The neuron-test command needs to be added to Gilgamesh CLI.")
            print("Run: gilgamesh --help  to see available commands.")
        return None

    if not csv_path.exists():
        print(f"Expected output not found: {csv_path}")
        return None

    return csv_path


def parse_gilgamesh_csv(csv_path: Path) -> Tuple[List[float], List[float], List[float]]:
    """Parse Gilgamesh CSV output."""
    times = []
    v_mem = []
    spikes = []

    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            times.append(float(row['time']))
            v_mem.append(float(row['membrane']))
            spikes.append(float(row.get('spike', 0)))

    return times, v_mem, spikes


def compute_metrics(
    t_spice: List[float], v_spice: List[float],
    t_rust: List[float], v_rust: List[float]
) -> dict:
    """Compute comparison metrics between SPICE and Rust traces."""
    import numpy as np

    # Interpolate to common time base
    t_common = np.linspace(
        max(t_spice[0], t_rust[0]),
        min(t_spice[-1], t_rust[-1]),
        min(len(t_spice), len(t_rust))
    )

    v_spice_interp = np.interp(t_common, t_spice, v_spice)
    v_rust_interp = np.interp(t_common, t_rust, v_rust)

    diff = v_spice_interp - v_rust_interp

    return {
        "rms_error": float(np.sqrt(np.mean(diff**2))),
        "max_abs_error": float(np.max(np.abs(diff))),
        "mean_abs_error": float(np.mean(np.abs(diff))),
        "correlation": float(np.corrcoef(v_spice_interp, v_rust_interp)[0, 1]),
        "num_samples": len(t_common)
    }


def plot_comparison(
    t_spice: List[float], v_spice: List[float],
    t_rust: List[float], v_rust: List[float],
    output_path: Path,
    metrics: dict,
    pulse_spice: List[float] = None,
    pulse_rust: List[float] = None,
):
    """Generate comparison plot with membrane and pulse outputs."""
    if not HAS_MATPLOTLIB:
        print("matplotlib not installed - skipping plot")
        return

    import numpy as np

    # Determine number of subplots based on available data
    has_pulse = pulse_spice is not None or pulse_rust is not None
    n_plots = 3 if has_pulse else 2

    fig, axes = plt.subplots(n_plots, 1, figsize=(12, 4 * n_plots), sharex=True)

    # Top: Membrane voltage overlay
    ax1 = axes[0]
    ax1.plot([t * 1000 for t in t_spice], v_spice, 'b-', label='SPICE v(mem)', linewidth=1.5)
    ax1.plot([t * 1000 for t in t_rust], v_rust, 'r--', label='Gilgamesh mem', linewidth=1.5)
    ax1.set_ylabel('Membrane Voltage (V)')
    ax1.set_title('Single LIF Neuron: SPICE vs Gilgamesh - Membrane Dynamics')
    ax1.legend(loc='upper right')
    ax1.grid(True, alpha=0.3)

    # Middle: Pulse/comparator output
    if has_pulse:
        ax2 = axes[1]
        if pulse_spice is not None:
            ax2.plot([t * 1000 for t in t_spice], pulse_spice, 'b-',
                     label='SPICE v(comp_pulse)', linewidth=1.5)
        if pulse_rust is not None:
            ax2.plot([t * 1000 for t in t_rust], pulse_rust, 'r--',
                     label='Gilgamesh pulse', linewidth=1.5)
        ax2.set_ylabel('Pulse Output (V)')
        ax2.set_title('Comparator / Pulse Stretcher Output')
        ax2.legend(loc='upper right')
        ax2.grid(True, alpha=0.3)
        ax2.set_ylim(-0.5, 5.5)  # Typical 0-5V range

        ax_diff = axes[2]
    else:
        ax_diff = axes[1]

    # Bottom: Difference
    t_common = np.linspace(
        max(t_spice[0], t_rust[0]),
        min(t_spice[-1], t_rust[-1]),
        min(len(t_spice), len(t_rust))
    )
    v_spice_interp = np.interp(t_common, t_spice, v_spice)
    v_rust_interp = np.interp(t_common, t_rust, v_rust)
    diff = v_spice_interp - v_rust_interp

    ax_diff.plot(t_common * 1000, diff * 1000, 'g-', linewidth=1)
    ax_diff.axhline(0, color='k', linestyle=':', linewidth=0.5)
    ax_diff.set_xlabel('Time (ms)')
    ax_diff.set_ylabel('Membrane Difference (mV)')
    ax_diff.set_title(f'Membrane Error: RMS={metrics["rms_error"]*1000:.3f}mV, Max={metrics["max_abs_error"]*1000:.3f}mV, Corr={metrics["correlation"]:.4f}')
    ax_diff.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
    print(f"Plot saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-current", type=float, default=1e-6,
                        help="Input current in Amps (default: 1e-6)")
    parser.add_argument("--duration", type=float, default=0.05,
                        help="Simulation duration in seconds (default: 0.05)")
    parser.add_argument("--dt", type=float, default=1e-6,
                        help="Timestep in seconds (default: 1e-6)")
    parser.add_argument("--tau-m", type=float, default=None,
                        help="Membrane time constant (default: computed from C*R)")
    parser.add_argument("--tau-pulse", type=float, default=1.67e-3,
                        help="Pulse stretch time constant (default: 1.67e-3)")
    parser.add_argument("--output-dir", type=Path, default=None,
                        help="Output directory (default: temp dir)")
    parser.add_argument("--keep-files", action="store_true",
                        help="Keep intermediate files")
    parser.add_argument("--skip-spice", action="store_true",
                        help="Skip SPICE simulation (use existing files)")
    parser.add_argument("--skip-rust", action="store_true",
                        help="Skip Gilgamesh simulation")

    args = parser.parse_args()

    # Set up parameters
    params = NeuronParams(
        input_current=args.input_current,
        duration=args.duration,
        dt=args.dt,
        tau_pulse=args.tau_pulse,
    )

    if args.tau_m:
        # Adjust C or R to match requested tau_m
        params.r_leak = args.tau_m / params.c_mem

    print("=== Single Neuron SPICE vs Gilgamesh Comparison ===")
    print(f"Parameters:")
    print(f"  tau_m = {params.tau_m * 1000:.3f} ms")
    print(f"  tau_pulse = {params.tau_pulse * 1000:.3f} ms")
    print(f"  threshold = {params.vref + params.threshold_over_vref:.2f} V")
    print(f"  input = {params.input_current * 1e6:.2f} uA")
    print(f"  duration = {params.duration * 1000:.1f} ms")
    print(f"  dt = {params.dt * 1e6:.1f} us")
    print()

    # Create output directory
    if args.output_dir:
        output_dir = args.output_dir
        output_dir.mkdir(parents=True, exist_ok=True)
    else:
        output_dir = Path(tempfile.mkdtemp(prefix="neuron_compare_"))

    print(f"Output directory: {output_dir}")

    # Run SPICE
    spice_csv = None
    if not args.skip_spice:
        netlist_path = generate_spice_netlist(params, output_dir)
        print(f"Generated netlist: {netlist_path}")
        spice_csv = run_ngspice(netlist_path, output_dir)
    else:
        spice_csv = output_dir / "spice_output.csv"
        if not spice_csv.exists():
            print(f"SPICE CSV not found: {spice_csv}")
            spice_csv = None

    # Run Gilgamesh
    rust_csv = None
    if not args.skip_rust:
        rust_csv = run_gilgamesh_neuron(params, output_dir)
    else:
        rust_csv = output_dir / "gilgamesh_output.csv"
        if not rust_csv.exists():
            print(f"Gilgamesh CSV not found: {rust_csv}")
            rust_csv = None

    # Compare results
    if spice_csv and rust_csv:
        print("\nParsing results...")
        t_spice, v_spice, _ = parse_spice_csv(spice_csv)
        t_rust, v_rust, _ = parse_gilgamesh_csv(rust_csv)

        print(f"SPICE: {len(t_spice)} samples")
        print(f"Gilgamesh: {len(t_rust)} samples")

        if t_spice and t_rust:
            metrics = compute_metrics(t_spice, v_spice, t_rust, v_rust)
            print("\n=== Comparison Metrics ===")
            print(f"  RMS Error:     {metrics['rms_error'] * 1000:.4f} mV")
            print(f"  Max Abs Error: {metrics['max_abs_error'] * 1000:.4f} mV")
            print(f"  Mean Abs Error:{metrics['mean_abs_error'] * 1000:.4f} mV")
            print(f"  Correlation:   {metrics['correlation']:.6f}")

            # Save metrics
            with open(output_dir / "metrics.json", 'w') as f:
                json.dump(metrics, f, indent=2)

            # Plot
            plot_comparison(
                t_spice, v_spice,
                t_rust, v_rust,
                output_dir / "comparison.png",
                metrics
            )
    elif spice_csv:
        print("\nOnly SPICE results available - plotting...")
        t_spice, v_spice, _ = parse_spice_csv(spice_csv)
        if HAS_MATPLOTLIB and t_spice:
            plt.figure(figsize=(10, 6))
            plt.plot([t * 1000 for t in t_spice], v_spice, 'b-')
            plt.xlabel('Time (ms)')
            plt.ylabel('Membrane Voltage (V)')
            plt.title('SPICE LIF Neuron Response')
            plt.grid(True, alpha=0.3)
            plt.savefig(output_dir / "spice_only.png", dpi=150)
            plt.close()
            print(f"Plot saved to: {output_dir / 'spice_only.png'}")

    # Cleanup
    if not args.keep_files and not args.output_dir:
        print(f"\nCleaning up temp directory: {output_dir}")
        shutil.rmtree(output_dir)
    else:
        print(f"\nFiles kept in: {output_dir}")


if __name__ == "__main__":
    main()
